services:
  - type: web
    name: my-spring-boot-app
    env: java
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/todo-tracer-0.0.1-SNAPSHOT.jar
    envVars:
      - key: DB_HOST
        value: dpg-cpv793lumphs73c7221g-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: task_traker
      - key: DB_USER
        value: user1
      - key: DB_PASSWORD
        value: 1B1HfQqttAtoZbNmtxOsJYYd91E71emJ
      - key: JAVA_HOME
        value: /opt/render/project/.jdk